# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------
language: python
group: edge
dist: trusty    

# executed. So things have to be tested oe by one.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      # For cmake
      - kubuntu-backports
    packages:
      - cmake
      - python-sphinx
      - graphviz
      - cpanminus

install:
  - pip install sphinx==1.6.5
  - pip install sphinx-intl
  - pip install sphinxjp.themes.revealjs
  - sudo cpanm -f -n Text::SimpleTable::AutoWidth

script: 
  - mkdir build
  - cd build
  #- cmake -DLOCALE=ON -DALL_DOC=ON -DALL_LANG=ON ..
  - cmake -DHTML=ON -DES=ON -DFR=ON -DDE=ON -DHU=ON -@OSGeoLiveDoc_DEBUG=ON ..
  - make
  - cd ..
  - bash scripts/clean-images.sh
  - touch build/doc/_build/html/.nojekyll # needed for gh pages to keep dirs starting with _
  - du -h build/doc/_build/html

# deploy to github pages - see https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir:  build/doc/_build/html/
  verbose: true
  on:
    branch: master # switch to master when ok
