# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------
language: python
group: edge
dist: trusty    

# executed. So things have to be tested oe by one.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      # For cmake
      - kubuntu-backports
    packages:
      - cmake
      - python-sphinx
      - graphviz
      - cpanminus

install:
  - pip install sphinx==1.6.5
  - pip install sphinx-intl
  - pip install sphinxjp.themes.revealjs
  - sudo cpanm -f -n Text::SimpleTable::AutoWidth

env:
  - LINKCHECK=ON
  - LINKCHECK=OFF    

script: 
  - mkdir build
  - cd build
  - bash ../ci/travis.sh

# deploy to github pages - see https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir:  build/doc/_build/html/
  verbose: true
  on:
    branch: master # switch to master when ok
    condition: $LINKCHECK = OFF
